'use strict';
const {test}=require('node:test');const assert=require('node:assert/strict');
const fs=require('node:fs');const os=require('node:os');const path=require('node:path');const net=require('node:net');const {spawn}=require('node:child_process');
test('HTTP app exercises actual lab operations and rejects cross-origin, host and CSRF violations',async t=>{
  const root=fs.mkdtempSync(path.join(os.tmpdir(),'canarygraph-http-'));
  const listener=net.createServer();await new Promise(r=>listener.listen(0,'127.0.0.1',r));const port=listener.address().port;await new Promise(r=>listener.close(r));
  const child=spawn(process.execPath,[path.resolve(__dirname,'../server.js')],{env:{...process.env,PORT:String(port),CANARYGRAPH_DATA:root},windowsHide:true,stdio:['ignore','pipe','pipe']});
  t.after(async()=>{const exited=new Promise(r=>child.once('exit',r));child.kill();if(child.exitCode===null)await exited;fs.rmSync(root,{recursive:true,force:true});});
  await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error('Startup timed out')),10000);child.stdout.on('data',d=>{if(d.toString().includes('running at')){clearTimeout(timer);resolve();}});child.once('error',reject);child.stderr.on('data',d=>{clearTimeout(timer);reject(new Error(d.toString()));});});
  const base=`http://127.0.0.1:${port}`;
  const page=await fetch(base);assert.equal(page.status,200);assert.match(await page.text(),/CanaryGraph/);assert.ok(page.headers.get('content-security-policy'));
  const state=await (await fetch(base+'/api/state')).json();
  const post=(route,data={},headers={})=>fetch(base+'/api/'+route,{method:'POST',headers:{'Content-Type':'application/json','X-CanaryGraph-Token':state.csrf,...headers},body:JSON.stringify(data)});
  assert.equal((await post('demo',{type:'intrusion'},{'X-CanaryGraph-Token':'wrong'})).status,403);
  assert.equal((await post('demo',{type:'intrusion'},{Origin:'https://untrusted.example'})).status,403);
  const wrongHostStatus=await new Promise((resolve,reject)=>{const req=require('node:http').get(base+'/api/state',{headers:{Host:'untrusted.example'}},res=>{res.resume();resolve(res.statusCode);});req.on('error',reject);});
  assert.equal(wrongHostStatus,403);
  assert.equal((await fetch(base+'/api/state',{headers:{Origin:'https://untrusted.example'}})).status,403);
  const session=await (await post('session')).json();
  assert.equal((await post('read',{session:session.session,asset:'../../server.js'})).status,400);
  assert.equal((await post('vault',{session:session.session})).status,400);
  assert.equal((await post('demo',{type:'intrusion'})).status,200);
  assert.equal((await post('demo',{type:'benign'})).status,200);
  const tamper=await (await post('tamper-demo')).json();assert.equal(tamper.original.ok,true);assert.equal(tamper.altered.ok,false);assert.equal(tamper.truncated.ok,false);
  const exported=await fetch(base+'/api/export');assert.match(exported.headers.get('content-disposition'),/attachment/);assert.equal((await exported.json()).events.length,8);
  assert.equal((await post('experiment',{seed:-2})).status,400);
  assert.equal((await (await post('experiment',{seed:42})).json()).rows.length,3);
  assert.equal((await (await post('verify')).json()).ok,true);
});
